//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FAMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FAMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.FAMessages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select whether to accept or not accept the offered terms..
        /// </summary>
        internal static string AcceptCounterTerms {
            get {
                return ResourceManager.GetString("AcceptCounterTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I hereby authorize [LenderName], its successors and assigns, to initiate a withdrawal for monies payable for the loan agreement referenced above to [LenderName]. The withdrawal shall be made from the above referenced Payment Account.  I understand that this authorization is solely for this single transaction. I understand that I may stop any payment by notifying [LenderName] or the financial institution holding my account 3 or more business days before my account is to be charged.  If your selected Payment  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ACHPaymentInvoiceAuthorizationInd {
            get {
                return ResourceManager.GetString("ACHPaymentInvoiceAuthorizationInd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We hereby authorize [LenderName], its successors and assigns, to initiate a withdrawal for monies payable for the loan agreement referenced above to [LenderName]. The withdrawal shall be made from the above referenced Payment Account.  We understand that this authorization is solely for this single transaction. We understand that we may stop any payment by notifying [LenderName] or the financial institution holding my account 3 or more business days before our account is to be charged.  If your selected Pay [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ACHPaymentInvoiceAuthorizationJoint {
            get {
                return ResourceManager.GetString("ACHPaymentInvoiceAuthorizationJoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As a reminder, when you submitted a joint application, you created a new User ID. Please use the new User ID and password to access the joint application..
        /// </summary>
        internal static string AddCoApplicantNewUserIdReminder {
            get {
                return ResourceManager.GetString("AddCoApplicantNewUserIdReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&quot;text-align: justify&quot;&gt;&lt;strong&gt;Notice to California Residents:&lt;/strong&gt;  California Law (Cal Civ Code § 1812.30) requires that you be informed that if you are married, you may apply for a separate account.&lt;/p&gt;.
        /// </summary>
        internal static string ApplicationDisclosure_California {
            get {
                return ResourceManager.GetString("ApplicationDisclosure_California", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&quot;text-align: justify&quot;&gt;&lt;strong&gt;Notice to Ohio Residents:&lt;/strong&gt;  The Ohio laws against discrimination require that all creditors make credit equally available to all creditworthy customers, and that credit reporting agencies maintain separate credit histories on each individual upon request.  The Ohio Civil Rights Commission administers compliance with this law.&lt;/p&gt;.
        /// </summary>
        internal static string ApplicationDisclosure_Ohio {
            get {
                return ResourceManager.GetString("ApplicationDisclosure_Ohio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&quot;text-align: justify&quot;&gt;&lt;strong&gt;Notice to Vermont Residents:&lt;/strong&gt;  Lender is engaged in loan production.&lt;/p&gt;.
        /// </summary>
        internal static string ApplicationDisclosure_Vermont {
            get {
                return ResourceManager.GetString("ApplicationDisclosure_Vermont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&quot;text-align: justify&quot;&gt;&lt;strong&gt;Married Wisconsin Residents:&lt;/strong&gt;  No provision of any marital property agreement, any unilateral statement under Wisconsin Stat. § 766.59 or a court decree under Wisconsin Stat. § 766.70 applied to marital property adversely affects our interest unless you furnish a copy of the agreement, statement or court decree to us or we have actual knowledge of such adverse provision before credit is granted. If you are making this application individually and not jointly wi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ApplicationDisclosure_Wisconsin {
            get {
                return ResourceManager.GetString("ApplicationDisclosure_Wisconsin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I hereby authorize [LenderName], its successors and assigns, to initiate withdrawals for monies payable for loan agreement referenced above to [LenderName].  Such withdrawals shall be made from the above referenced Payment Account or such other account that I designate in the future to which I am a signatory.  I understand that this authorization will remain in effect until I notify [LenderName] to cancel it by emailing [EmailAddress] and [LenderName] is given a reasonable time to effect such cancellation.  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AutoPayAuthorizationInd {
            get {
                return ResourceManager.GetString("AutoPayAuthorizationInd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We hereby authorize [LenderName], its successors and assigns, to initiate withdrawals for monies payable for loan agreement referenced above to [LenderName].  Such withdrawals shall be made from the above referenced Payment Account or such other account that we designate in the future to which one or both or us are a signatory.  We understand that this authorization will remain in effect until we notify [LenderName] to cancel it by emailing [EmailAddress] and [LenderName] is given a reasonable time to effec [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AutoPayAuthorizationJoint {
            get {
                return ResourceManager.GetString("AutoPayAuthorizationJoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Passcode you have entered is invalid.  Please review the information entered, make any corrections, and select submit..
        /// </summary>
        internal static string BadPassCode {
            get {
                return ResourceManager.GetString("BadPassCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Password must not resemble your name, user ID or email address..
        /// </summary>
        internal static string ChangePasswordResemble_Val {
            get {
                return ResourceManager.GetString("ChangePasswordResemble_Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password entered is invalid, please review and re-enter your password.  See Password Help if you need assistance..
        /// </summary>
        internal static string ChangePassword_Val {
            get {
                return ResourceManager.GetString("ChangePassword_Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a question and/or comment.  Thank You.
        /// </summary>
        internal static string ContactUsComment_Val {
            get {
                return ResourceManager.GetString("ContactUsComment_Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightStream.
        /// </summary>
        internal static string ContactUsCustomerService {
            get {
                return ResourceManager.GetString("ContactUsCustomerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email address.&lt;br/&gt;.
        /// </summary>
        internal static string ContactUsEmailMissing_Val {
            get {
                return ResourceManager.GetString("ContactUsEmailMissing_Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address, please re-enter.&lt;br/&gt;.
        /// </summary>
        internal static string ContactUsEmail_Val {
            get {
                return ResourceManager.GetString("ContactUsEmail_Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your name.
        /// </summary>
        internal static string ContactUsName_Val {
            get {
                return ResourceManager.GetString("ContactUsName_Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LightStream.
        /// </summary>
        internal static string ContactUsPrivacyGroup {
            get {
                return ResourceManager.GetString("ContactUsPrivacyGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your decline notice is not yet available, please try again in a few minutes..
        /// </summary>
        internal static string DeclineNoticeNotYetAvailable {
            get {
                return ResourceManager.GetString("DeclineNoticeNotYetAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In the event that we are unable to approve your loan request, please check this box if you would like us to share your application information with third parties to assist you in getting a loan.  By checking this box, you understand we may receive a fee and agree:&lt;br /&gt;1. The third parties can contact you by phone and/or email;&lt;br /&gt;2. The Statement on the Use of Electronic Records, and the consents and notices below, apply to any third party to which we refer you;&lt;br&gt;3. You are authorizing the third partie [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeclineReferralOptIn {
            get {
                return ResourceManager.GetString("DeclineReferralOptIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address you have entered does not match the email address we have on file. Please review the information entered, make any corrections, and select submit..
        /// </summary>
        internal static string EmailAddressNotFound {
            get {
                return ResourceManager.GetString("EmailAddressNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Florida &lt;a href=&quot;{0}&quot; data-popup=&quot;true&quot; data-height=&quot;300&quot; data-width=&quot;400&quot;&gt;documentary stamp tax&lt;/a&gt; in the amount of {1:C} will be added to your loan amount then transmitted for payment on your behalf. Stamp tax is &lt;u&gt;not&lt;/u&gt; included when determining loan interest rate..
        /// </summary>
        internal static string FloridaDocStampAppDisclosure {
            get {
                return ResourceManager.GetString("FloridaDocStampAppDisclosure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Florida &lt;a href=&quot;{0}&quot; data-popup=&quot;true&quot; data-height=&quot;300&quot; data-width=&quot;400&quot;&gt;documentary stamp tax&lt;/a&gt; which we are required to collect and transmit to the State of Florida on your behalf, in the amount of {1:C}, will be added to your loan amount and will slightly increase the monthly payment. Stamp tax is &lt;u&gt;not&lt;/u&gt; included when determining loan interest rate.  You will see this in the Disclosures section of your loan agreement..
        /// </summary>
        internal static string FloridaDocStampDisclosure {
            get {
                return ResourceManager.GetString("FloridaDocStampDisclosure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are sorry but an error has occurred and we are unable to process your request. Please try again..
        /// </summary>
        internal static string GenericError {
            get {
                return ResourceManager.GetString("GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct or complete all red highlighted fields before selecting Next..
        /// </summary>
        internal static string LoanAppHintError {
            get {
                return ResourceManager.GetString("LoanAppHintError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were unable to approve your loan application for the terms requested. For additional information, please view the decline notice via the link to your left..
        /// </summary>
        internal static string LoanCounterDecline {
            get {
                return ResourceManager.GetString("LoanCounterDecline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were unable to approve your loan application for the terms requested. For additional information, please view your respective decline notices via the links to your left. .
        /// </summary>
        internal static string LoanCounterJointDecline {
            get {
                return ResourceManager.GetString("LoanCounterJointDecline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You for accepting the Loan Offer &lt;font color=&apos;red&apos;&gt;TEXT TBD &lt;/font&gt;.
        /// </summary>
        internal static string LoanOfferAccepted {
            get {
                return ResourceManager.GetString("LoanOfferAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name is required.
        /// </summary>
        internal static string LoanOfferAccountName_Req {
            get {
                return ResourceManager.GetString("LoanOfferAccountName_Req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account number is required.
        /// </summary>
        internal static string LoanOfferAccountNumber_Req {
            get {
                return ResourceManager.GetString("LoanOfferAccountNumber_Req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account number invalid, please re-enter your account #.
        /// </summary>
        internal static string LoanOfferAccountNumber_Val {
            get {
                return ResourceManager.GetString("LoanOfferAccountNumber_Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid address, please re-enter.
        /// </summary>
        internal static string LoanOfferAddress_Val {
            get {
                return ResourceManager.GetString("LoanOfferAddress_Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must accept the automated authorization agreement to proceed.
        /// </summary>
        internal static string LoanOfferAutomatedAgreement_Req {
            get {
                return ResourceManager.GetString("LoanOfferAutomatedAgreement_Req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your loan application has been cancelled..
        /// </summary>
        internal static string LoanOfferCancelled {
            get {
                return ResourceManager.GetString("LoanOfferCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We hope we can serve you in the future..
        /// </summary>
        internal static string LoanOfferCancelledParagraph2 {
            get {
                return ResourceManager.GetString("LoanOfferCancelledParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid card code, please re-enter.
        /// </summary>
        internal static string LoanOfferCardCode_Val {
            get {
                return ResourceManager.GetString("LoanOfferCardCode_Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credit card number, please re-enter.
        /// </summary>
        internal static string LoanOfferCC_Val {
            get {
                return ResourceManager.GetString("LoanOfferCC_Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid city, please re-enter.
        /// </summary>
        internal static string LoanOfferCity_Val {
            get {
                return ResourceManager.GetString("LoanOfferCity_Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credit card expiration date, please re-enter.
        /// </summary>
        internal static string LoanOfferExpirationDate_Val {
            get {
                return ResourceManager.GetString("LoanOfferExpirationDate_Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your loan proceeds will be deposited on, {0}.  Depending on the bank, your funds may be available a day early, please confirm receipt of the loan proceeds directly with your bank..
        /// </summary>
        internal static string LoanOfferFundingConfirmation {
            get {
                return ResourceManager.GetString("LoanOfferFundingConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are unable to verify your credit card..
        /// </summary>
        internal static string LoanOfferInvalidCC1 {
            get {
                return ResourceManager.GetString("LoanOfferInvalidCC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact your credit card company for assistance.&lt;br&gt;Thank You.
        /// </summary>
        internal static string LoanOfferInvalidCC2 {
            get {
                return ResourceManager.GetString("LoanOfferInvalidCC2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a valid Visa or MasterCard number..
        /// </summary>
        internal static string LoanOfferInvalidMCOrVisaNumber {
            get {
                return ResourceManager.GetString("LoanOfferInvalidMCOrVisaNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your loan application with LightStream has been approved!.
        /// </summary>
        internal static string LoanOfferLoanApplicationApproved {
            get {
                return ResourceManager.GetString("LoanOfferLoanApplicationApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To accept the loan terms below simply (1) &lt;a href=&quot;Default.aspx?Proceed=true&amp;ctx={0}&quot;&gt;Proceed to Loan Agreement&lt;/a&gt; to review and electronically sign your loan agreement; (2) go to Account Set Up and provide us with your preferences - funding date, banking information, monthly payment date, etc. and; (3) complete the final verification process..
        /// </summary>
        internal static string LoanOfferLoanApplicationApprovedParagraph2 {
            get {
                return ResourceManager.GetString("LoanOfferLoanApplicationApprovedParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may fund your loan the same day you complete the above process, if that day is a banking business day, and the final verification process is completed by {0}.  Otherwise, feel free to set-up your loan for funding at anytime, for any available day..
        /// </summary>
        internal static string LoanOfferLoanApplicationApprovedParagraph3 {
            get {
                return ResourceManager.GetString("LoanOfferLoanApplicationApprovedParagraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Would you like your loan proceeds today?&lt;/b&gt;&lt;br /&gt;&lt;br /&gt;You can fund your loan today, if you complete the above steps before {0}.  Just be sure to select today&apos;s date during account set up or, if you prefer, you may choose any other available day..
        /// </summary>
        internal static string LoanOfferLoanApplicationApprovedParagraph3_SameDay {
            get {
                return ResourceManager.GetString("LoanOfferLoanApplicationApprovedParagraph3_SameDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new loan terms request that you recently submitted is currently in process.  You will receive an email response {0}.  Thank you..
        /// </summary>
        internal static string LoanOfferLoanRequestPending {
            get {
                return ResourceManager.GetString("LoanOfferLoanRequestPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To begin the funding process, please &lt;a href=&quot;Default.aspx?Proceed=true&amp;ctx={0}&quot;&gt;Proceed to Loan Agreement&lt;/a&gt;..
        /// </summary>
        internal static string LoanOfferLoanTermsApprovedParagraph2 {
            get {
                return ResourceManager.GetString("LoanOfferLoanTermsApprovedParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid monthly payment, please re-enter.
        /// </summary>
        internal static string LoanOfferMonthlyPayment_Req {
            get {
                return ResourceManager.GetString("LoanOfferMonthlyPayment_Req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter the name on the credit card.
        /// </summary>
        internal static string LoanOfferName_Req {
            get {
                return ResourceManager.GetString("LoanOfferName_Req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are unable to approve the new loan terms that you requested, however, your previous approved terms are available and ready for your use.  To continue with your previous terms and begin the funding set up of your loan, select &lt;a href=&quot;Default.aspx?Continue=true&amp;ctx={0}&quot;&gt;Continue with Previous Terms&lt;/a&gt;..
        /// </summary>
        internal static string LoanOfferNewLoanTermsRejected {
            get {
                return ResourceManager.GetString("LoanOfferNewLoanTermsRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may fund your loan the same day you complete the funding set up, if that day is a banking business day, and the final verification process is completed by {0}.  Otherwise, feel free to set-up your loan for funding at anytime, for any available day..
        /// </summary>
        internal static string LoanOfferNewLoanTermsRejectedParagraph2 {
            get {
                return ResourceManager.GetString("LoanOfferNewLoanTermsRejectedParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Would you like your loan proceeds today?&lt;/b&gt;&lt;br /&gt;&lt;br /&gt;You can fund your loan today, if you complete the funding set up before {0}.  Just be sure to select today&apos;s date on the account set up tab, or, if you prefer, you may choose any other available date..
        /// </summary>
        internal static string LoanOfferNewLoanTermsRejectedParagraph2_SameDay {
            get {
                return ResourceManager.GetString("LoanOfferNewLoanTermsRejectedParagraph2_SameDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To view the reasons your new loan terms request was not approved, &lt;a href=&apos;../../ENotices/Default.aspx?page=declinenotices&amp;ltr={0}&amp;ctx={1}&apos; target=&apos;_new&apos; onclick=&quot;OpenWindow(this.href, this.target, 800, 520, -1, -1,&apos;status=yes,menubar=yes,scrollbars=yes,resizable=yes&apos;)&quot;&gt;click here.&lt;/a&gt;.
        /// </summary>
        internal static string LoanOfferNewLoanTermsRejectedParagraph3 {
            get {
                return ResourceManager.GetString("LoanOfferNewLoanTermsRejectedParagraph3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To continue with your previous terms and begin the funding set up of your loan, select &lt;a href=&quot;Default.aspx?Continue=true&amp;ctx={0}&quot;&gt;Continue with Previous Terms&lt;/a&gt;..
        /// </summary>
        internal static string LoanOfferNewLoanTermsRequestCancelled {
            get {
                return ResourceManager.GetString("LoanOfferNewLoanTermsRequestCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your recently submitted loan application.  We are in the process of reviewing your information and have a few questions..
        /// </summary>
        internal static string LoanOfferNewRequestPendingQuestion {
            get {
                return ResourceManager.GetString("LoanOfferNewRequestPendingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact us at [PHONE_NUMBER].  Our business hours are [BUSINESS_HOURS].  Thank you.
        /// </summary>
        internal static string LoanOfferNewRequestPendingQuestionParagraph2 {
            get {
                return ResourceManager.GetString("LoanOfferNewRequestPendingQuestionParagraph2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your new loan terms request has been received.  We will email you {0} regarding our credit decision, or questions that we may have..
        /// </summary>
        internal static string LoanOfferNewTermNotAutoApproved {
            get {
                return ResourceManager.GetString("LoanOfferNewTermNotAutoApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new loan terms you requested have been approved!.
        /// </summary>
        internal static string LoanOfferNewTermsApproved {
            get {
                return ResourceManager.GetString("LoanOfferNewTermsApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter an active credit card, please re-enter.
        /// </summary>
        internal static string LoanOfferPastExpirationDate_Val {
            get {
                return ResourceManager.GetString("LoanOfferPastExpirationDate_Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a funding date.
        /// </summary>
        internal static string LoanOfferPaymentDate_Req {
            get {
                return ResourceManager.GetString("LoanOfferPaymentDate_Req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To cancel your loan application, please select a cancel reason.
        /// </summary>
        internal static string LoanOfferReasons_Req {
            get {
                return ResourceManager.GetString("LoanOfferReasons_Req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Routing number is required.
        /// </summary>
        internal static string LoanOfferRoutingNumber_Req {
            get {
                return ResourceManager.GetString("LoanOfferRoutingNumber_Req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;font color=&apos;red&apos;&gt;The number entered is invalid, please re-enter.&lt;/font&gt;.
        /// </summary>
        internal static string LoanOfferRoutingNumber_Val {
            get {
                return ResourceManager.GetString("LoanOfferRoutingNumber_Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your security answer.&lt;br/&gt;.
        /// </summary>
        internal static string LoanOfferSecurityAnswer_Req {
            get {
                return ResourceManager.GetString("LoanOfferSecurityAnswer_Req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid security answer, please re-enter.
        /// </summary>
        internal static string LoanOfferSecurityAnswer_Val {
            get {
                return ResourceManager.GetString("LoanOfferSecurityAnswer_Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid state, please re-enter.
        /// </summary>
        internal static string LoanOfferState_Val {
            get {
                return ResourceManager.GetString("LoanOfferState_Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you from all of us at FirstAgain.&lt;br&gt; &lt;i&gt;Where our service proudly put you first again..
        /// </summary>
        internal static string LoanOfferThankyou {
            get {
                return ResourceManager.GetString("LoanOfferThankyou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid unit #, please re-enter.
        /// </summary>
        internal static string LoanOfferUnit_Val {
            get {
                return ResourceManager.GetString("LoanOfferUnit_Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid zip code, please re-enter.
        /// </summary>
        internal static string LoanOfferZip_Val {
            get {
                return ResourceManager.GetString("LoanOfferZip_Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your recently submitted loan application.
        ///Your application is currently being processed..
        /// </summary>
        internal static string LoanPending {
            get {
                return ResourceManager.GetString("LoanPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your recently submitted loan application. We are in the process of reviewing your information and have a few questions..
        /// </summary>
        internal static string LoanPendingQ1 {
            get {
                return ResourceManager.GetString("LoanPendingQ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact us at [PHONE_NUMBER]. Our business hours are [BUSINESS_HOURS]..
        /// </summary>
        internal static string LoanPendingQ2 {
            get {
                return ResourceManager.GetString("LoanPendingQ2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your loan application has been approved for the maximum loan amount.  You may request a lower amount, change your term, or form of payment..
        /// </summary>
        internal static string LoanTerms_Approved_ForMaxAmount {
            get {
                return ResourceManager.GetString("LoanTerms_Approved_ForMaxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your loan application has been approved for the loan terms below. You may also request a change to these loan terms by submitting your request below..
        /// </summary>
        internal static string LoanTerms_Approved_SecuredAuto {
            get {
                return ResourceManager.GetString("LoanTerms_Approved_SecuredAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your loan application has been approved for the loan terms below.  You may also request a change to these loan terms by submitting your request below..
        /// </summary>
        internal static string LoanTerms_ChangeTerms {
            get {
                return ResourceManager.GetString("LoanTerms_ChangeTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your loan application has been approved for the loan terms below.  You may also request a change to these loan terms by submitting your request below..
        /// </summary>
        internal static string LoanTerms_ChangeTerms_Prefunding {
            get {
                return ResourceManager.GetString("LoanTerms_ChangeTerms_Prefunding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your loan application has been approved for the maximum loan amount of {0}. You may request a loan amount equal to or less than this amount, change your term, or form of payment..
        /// </summary>
        internal static string LoanTerms_Current_Below_Counter {
            get {
                return ResourceManager.GetString("LoanTerms_Current_Below_Counter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a loan amount between {0} and {1}.
        /// </summary>
        internal static string LoanTerms_InvalidAmount {
            get {
                return ResourceManager.GetString("LoanTerms_InvalidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum loan amount in {0} is {1}.  Please enter an amount between {2} and {3}..
        /// </summary>
        internal static string LoanTerms_InvalidAmountStateMax {
            get {
                return ResourceManager.GetString("LoanTerms_InvalidAmountStateMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum loan amount in {0} is {1}.  Please enter an amount between {2} and {3}..
        /// </summary>
        internal static string LoanTerms_InvalidAmountStateMin {
            get {
                return ResourceManager.GetString("LoanTerms_InvalidAmountStateMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a loan term from {0} to {1} months.
        /// </summary>
        internal static string LoanTerms_InvalidTerm {
            get {
                return ResourceManager.GetString("LoanTerms_InvalidTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum loan term in {0} is {1} months.  Please enter a term between {2} and {3} months..
        /// </summary>
        internal static string LoanTerms_InvalidTermStateMax {
            get {
                return ResourceManager.GetString("LoanTerms_InvalidTermStateMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your Passcode.&lt;br/&gt;.
        /// </summary>
        internal static string MissingPassCode {
            get {
                return ResourceManager.GetString("MissingPassCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your new email address.&lt;br/&gt;.
        /// </summary>
        internal static string NewEmailMissing_Val {
            get {
                return ResourceManager.GetString("NewEmailMissing_Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your participation in our customer testimonial is very much appreciated..
        /// </summary>
        internal static string OptInToTestimonialPgm {
            get {
                return ResourceManager.GetString("OptInToTestimonialPgm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Birthday e-Greeting Preferences have automatically been updated. You will no longer receive birthday e-greetings from FirstAgain..
        /// </summary>
        internal static string OptOutOfBirthdayGreetings {
            get {
                return ResourceManager.GetString("OptOutOfBirthdayGreetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Holiday e-Greeting Preferences have automatically been updated.  You will no longer receive holiday e-greetings from FirstAgain..
        /// </summary>
        internal static string OptOutOfHolidayGreetings {
            get {
                return ResourceManager.GetString("OptOutOfHolidayGreetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your preferences have been updated and, as requested, you will no longer receive email surveys from FirstAgain..
        /// </summary>
        internal static string OptOutOfSurveys {
            get {
                return ResourceManager.GetString("OptOutOfSurveys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please re-enter your Password..
        /// </summary>
        internal static string PasswordChangeReEnter_Val {
            get {
                return ResourceManager.GetString("PasswordChangeReEnter_Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;IMPORTANT!&lt;br /&gt;&lt;br /&gt;Do NOT have LightStream listed as a lienholder on your vehicle title or loss payee on your insurance policy. If {0} insurance company inquires, just tell them that you did NOT use secured financing. This will save each of us paperwork hassles in the future. Thanks!.
        /// </summary>
        internal static string PreFundingInfo_LoanPurpose_Message {
            get {
                return ResourceManager.GetString("PreFundingInfo_LoanPurpose_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the last four digits of your driver&apos;s license..
        /// </summary>
        internal static string RecoverUserIdDrivers_Val {
            get {
                return ResourceManager.GetString("RecoverUserIdDrivers_Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We found no matching records. Please  review and re-enter your information. &lt;br /&gt;.
        /// </summary>
        internal static string RecoverUserIdNotFound_Val {
            get {
                return ResourceManager.GetString("RecoverUserIdNotFound_Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your social security number..
        /// </summary>
        internal static string RecoverUserIdSocial_Val {
            get {
                return ResourceManager.GetString("RecoverUserIdSocial_Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your Password..
        /// </summary>
        internal static string SignInPassword_Val {
            get {
                return ResourceManager.GetString("SignInPassword_Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your User Id..
        /// </summary>
        internal static string SignInUserId_Val {
            get {
                return ResourceManager.GetString("SignInUserId_Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application is no longer in the expected status. Please log in again to continue..
        /// </summary>
        internal static string UnexpectedStatusError {
            get {
                return ResourceManager.GetString("UnexpectedStatusError", resourceCulture);
            }
        }
    }
}
