//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LoanAppErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoanAppErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.LoanAppErrorMessages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected funding date is now only available as a wire transfer.  Please select another date if you wish to avoid possible wire transfer fees.  Thank You..
        /// </summary>
        internal static string ACHFundingDateExpired {
            get {
                return ResourceManager.GetString("ACHFundingDateExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, your banking institution does not support wire transfers, please select another eligible date from the calendar.  Thank you..
        /// </summary>
        internal static string BankDoesNotSupportWire {
            get {
                return ResourceManager.GetString("BankDoesNotSupportWire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct or complete all red highlighted fields before selecting save..
        /// </summary>
        internal static string ErrorCorrectCompleteAllRedFields {
            get {
                return ResourceManager.GetString("ErrorCorrectCompleteAllRedFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user ID you selected is unavailable. Please select another user ID, thank you..
        /// </summary>
        internal static string ErrorCustomerUserIdExists {
            get {
                return ResourceManager.GetString("ErrorCustomerUserIdExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user ID you entered is invalid. Please re-enter. Review the user ID help &lt;img src=&quot;../Assets/Images/icon_information.gif&quot; align=&quot;top&quot; style=&quot;display:inline&quot;/&gt;, if you need assistance..
        /// </summary>
        internal static string ErrorCustomerUserIdRegEx {
            get {
                return ResourceManager.GetString("ErrorCustomerUserIdRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Birth.
        /// </summary>
        internal static string ErrorDateOfBirth {
            get {
                return ResourceManager.GetString("ErrorDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicant must be 18 years of age to apply for a LightStream loan..
        /// </summary>
        internal static string ErrorDateOfBirthLT18 {
            get {
                return ResourceManager.GetString("ErrorDateOfBirthLT18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address entered is invalid. Please reenter..
        /// </summary>
        internal static string ErrorEmailAddressVal {
            get {
                return ResourceManager.GetString("ErrorEmailAddressVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A P.O. Box is not a valid street address, please re-enter the information..
        /// </summary>
        internal static string ErrorEmployerAddressLine1NoPO {
            get {
                return ResourceManager.GetString("ErrorEmployerAddressLine1NoPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The street address is invalid, please re-enter the information..
        /// </summary>
        internal static string ErrorEmployerAddressLine1Val {
            get {
                return ResourceManager.GetString("ErrorEmployerAddressLine1Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company city must be &quot;APO&quot; or &quot;FPO&quot; when the company state is AA, AE, or AP..
        /// </summary>
        internal static string ErrorEmployerCityStateMilitary {
            get {
                return ResourceManager.GetString("ErrorEmployerCityStateMilitary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Bldg, Floor, Mail Stop, or Suite from the drop down box..
        /// </summary>
        internal static string ErrorEmployerPostalUnitType {
            get {
                return ResourceManager.GetString("ErrorEmployerPostalUnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a Bldg, Floor, Mail Stop, or Suite number..
        /// </summary>
        internal static string ErrorEmployerPostalUnitValue {
            get {
                return ResourceManager.GetString("ErrorEmployerPostalUnitValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the current equity in your home. If none, please enter zero..
        /// </summary>
        internal static string ErrorEquityInHome {
            get {
                return ResourceManager.GetString("ErrorEquityInHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The equity entered is invalid, please re-enter the information..
        /// </summary>
        internal static string ErrorEquityInHomeVal {
            get {
                return ResourceManager.GetString("ErrorEquityInHomeVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name entered is invalid, please re-enter the applicant&apos;s first name..
        /// </summary>
        internal static string ErrorFirstNameVal {
            get {
                return ResourceManager.GetString("ErrorFirstNameVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name entered in invalid, please re-enter the applicant&apos;s last name..
        /// </summary>
        internal static string ErrorLastNameVal {
            get {
                return ResourceManager.GetString("ErrorLastNameVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a loan amount between {MINIMUM} and $100,000.00.
        /// </summary>
        internal static string ErrorLoanAmountRange {
            get {
                return ResourceManager.GetString("ErrorLoanAmountRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a loan term between {MINIMUM} and {MAXIMUM} months..
        /// </summary>
        internal static string ErrorLoanTermRange {
            get {
                return ResourceManager.GetString("ErrorLoanTermRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The middle initial entered is invalid, please re-enter the middle initial..
        /// </summary>
        internal static string ErrorMiddleInitial {
            get {
                return ResourceManager.GetString("ErrorMiddleInitial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The estimated monthly housing cost entered is invalid, please re-enter the information..
        /// </summary>
        internal static string ErrorMonthlyHousingCostVal {
            get {
                return ResourceManager.GetString("ErrorMonthlyHousingCostVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a dollar amount for &amp;quot;Other Annual Income&amp;quot;.
        /// </summary>
        internal static string ErrorOtherAnnualIncome {
            get {
                return ResourceManager.GetString("ErrorOtherAnnualIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other annual income information is required..
        /// </summary>
        internal static string ErrorOtherAnnualIncomeRequired {
            get {
                return ResourceManager.GetString("ErrorOtherAnnualIncomeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords entered do not match. Please re-enter your passwords. Thank you..
        /// </summary>
        internal static string ErrorPasswordNoMatch {
            get {
                return ResourceManager.GetString("ErrorPasswordNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password you entered is invalid. Please re-enter. Review the password help if you need assistance..
        /// </summary>
        internal static string ErrorPasswordRegEx {
            get {
                return ResourceManager.GetString("ErrorPasswordRegEx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We do not accept P.O. Boxes as the street address. .
        /// </summary>
        internal static string ErrorResAddressLine1NoPO {
            get {
                return ResourceManager.GetString("ErrorResAddressLine1NoPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The street address must begin with a number or the letter R. .
        /// </summary>
        internal static string ErrorResAddressLine1Val {
            get {
                return ResourceManager.GetString("ErrorResAddressLine1Val", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Apt, Suite or Unit from the drop down box..
        /// </summary>
        internal static string ErrorResPostalUnitType {
            get {
                return ResourceManager.GetString("ErrorResPostalUnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an apartment, suite, or unit number..
        /// </summary>
        internal static string ErrorResPostalUnitValue {
            get {
                return ResourceManager.GetString("ErrorResPostalUnitValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We do not accept military residential addresses..
        /// </summary>
        internal static string ErrorResZipCodeMilitary {
            get {
                return ResourceManager.GetString("ErrorResZipCodeMilitary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip code entered not found, please review your zip code and enter your state of residence..
        /// </summary>
        internal static string ErrorResZipCodeNotFound {
            get {
                return ResourceManager.GetString("ErrorResZipCodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The zip code entered does not match the state entered.  Please review and correct..
        /// </summary>
        internal static string ErrorResZipCodeStateNoMatch {
            get {
                return ResourceManager.GetString("ErrorResZipCodeStateNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The zip code entered is invalid, please enter your 5 digit zip code..
        /// </summary>
        internal static string ErrorResZipCodeVal {
            get {
                return ResourceManager.GetString("ErrorResZipCodeVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter zero or more for the amount of your retirement assets..
        /// </summary>
        internal static string ErrorRetirementAssets {
            get {
                return ResourceManager.GetString("ErrorRetirementAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The same social security number cannot be entered for both applicants..
        /// </summary>
        internal static string ErrorSameApplicantSocialSecurityNumber {
            get {
                return ResourceManager.GetString("ErrorSameApplicantSocialSecurityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Security Number is not entered or is invalid..
        /// </summary>
        internal static string ErrorSocialSecurityNumber {
            get {
                return ResourceManager.GetString("ErrorSocialSecurityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time at Current Address must  be at least one month..
        /// </summary>
        internal static string ErrorTimeAtRes {
            get {
                return ResourceManager.GetString("ErrorTimeAtRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time at Current Company must be at least one month..
        /// </summary>
        internal static string ErrorTimeWithEmployer {
            get {
                return ResourceManager.GetString("ErrorTimeWithEmployer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are sorry, the funding date selected is no longer available, please choose a new date from the calendar..
        /// </summary>
        internal static string FundingDateNotAvailable {
            get {
                return ResourceManager.GetString("FundingDateNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can only consider the assets and incomes of individuals who are applicants for the requested loan.
        /// </summary>
        internal static string HintApplicationType {
            get {
                return ResourceManager.GetString("HintApplicationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your equity is the difference between the estimated market value of your home, less the balance of any outstanding mortgages, including home equity loans..
        /// </summary>
        internal static string HintEquityInHome {
            get {
                return ResourceManager.GetString("HintEquityInHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Includes the sum of checking and savings accounts, stocks and bonds. Do not include the value of any home equity, auto(s), 401(k) or IRAs..
        /// </summary>
        internal static string HintLiquidAssets {
            get {
                return ResourceManager.GetString("HintLiquidAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimate, in the case of homeowners, of all monthly mortgage payments, including first mortgages, second mortgages, and home equity loans.  Renters, please enter monthly rent..
        /// </summary>
        internal static string HintMonthlyHousingCost {
            get {
                return ResourceManager.GetString("HintMonthlyHousingCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A non-resident alien is a non-U.S. citizen who has been issued an alien registration card, otherwise known as a green card, or a valid social security number (not an ITIN)..
        /// </summary>
        internal static string HintNonResidentAlien {
            get {
                return ResourceManager.GetString("HintNonResidentAlien", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Non Owner Occupied for second homes, vacation homes, and rental properties..
        /// </summary>
        internal static string HintOccupancyType {
            get {
                return ResourceManager.GetString("HintOccupancyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other annual income may include bonuses, commissions, tips, interest, dividends, alimony, child support, etc..
        /// </summary>
        internal static string HintOtherAnnualIncome {
            get {
                return ResourceManager.GetString("HintOtherAnnualIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please do not include non-applicant income..
        /// </summary>
        internal static string HintOtherAnnualIncomeNonApplicant {
            get {
                return ResourceManager.GetString("HintOtherAnnualIncomeNonApplicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other income may include retirement pay, pension, Social Security, interest, dividends, alimony, child support, etc..
        /// </summary>
        internal static string HintOtherAnnualIncomeRetired {
            get {
                return ResourceManager.GetString("HintOtherAnnualIncomeRetired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example of non-taxable income include but are not limited to: &lt;ul class=passwordHint&gt;&lt;li&gt;Non-taxable social security benefits and disability payments&lt;/li&gt;&lt;li&gt;Certain military allowances&lt;/li&gt;&lt;li&gt;Child support payments&lt;/li&gt;&lt;li&gt;Worker&apos;s compensation benefits&lt;/li&gt;&lt;li&gt;Disability retirement payment&lt;/li&gt;&lt;li&gt;Certain types of public assistance payments&lt;/li&gt;&lt;li&gt;Tax exempt interest earnings&lt;/li&gt;&lt;/ul&gt;.
        /// </summary>
        internal static string HintOtherAnnualIncomeTaxExempt {
            get {
                return ResourceManager.GetString("HintOtherAnnualIncomeTaxExempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password should be difficult to guess and follow these guidelines:&lt;ul class=passwordHint&gt;&lt;li&gt;It must contain at least 1 letter AND 1 number.&lt;/li&gt;&lt;li&gt;It cannot be the same as your user ID.&lt;li&gt;It must consist of only the following characters 0-9 &lt;nobr&gt;a-z&lt;/nobr&gt; &lt;nobr&gt;! &amp; $  - . _.&lt;/nobr&gt;&lt;/li&gt;&lt;li&gt;It may contain spaces.&lt;/li&gt;&lt;li&gt;It is not case sensitive (that is, upper and lower case versions of letters are treated the same).&lt;/li&gt;&lt;/ul&gt;.
        /// </summary>
        internal static string HintPassword {
            get {
                return ResourceManager.GetString("HintPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose AutoPay and save. With our AutoPay option, your monthly loan payments are conveniently deducted from your designated account..
        /// </summary>
        internal static string HintPaymentType {
            get {
                return ResourceManager.GetString("HintPaymentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select One To Four Family Dwelling for loans on houses, individual condominiums, apartments, or cooperative units..
        /// </summary>
        internal static string HintPropertyType {
            get {
                return ResourceManager.GetString("HintPropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retirement Assets include only monies that exist today and are 100 percent vested and owned by you. .
        /// </summary>
        internal static string HintRetirementAssets {
            get {
                return ResourceManager.GetString("HintRetirementAssets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your security answer:&lt;ul class=passwordHint&gt;&lt;li&gt;may contain only the following characters; 0-9, a-z, &lt;nobr&gt;! &amp; $ , - . _.&lt;/nobr&gt;&lt;/li&gt;&lt;li&gt;may contain spaces.&lt;/li&gt;&lt;li&gt;is not case sensitive (that is, upper and lower case versions of letters are treated the same).&lt;/li&gt;&lt;/ul&gt;.
        /// </summary>
        internal static string HintSecurityAnswer {
            get {
                return ResourceManager.GetString("HintSecurityAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For privacy purposes, a user ID cannot have more than 2 individuals associated with it. This user ID already has 2 individuals assoicated with it..
        /// </summary>
        internal static string HintSubmitForJoint {
            get {
                return ResourceManager.GetString("HintSubmitForJoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your user ID must be unique and should be difficult to guess. Consider mixing numbers, letters, and other characters.  &lt;br /&gt;Your user ID:&lt;ul class=passwordHint&gt;&lt;li&gt;may contain only the following characters;&lt;br /&gt; 0-9, a-z, ! &amp; $ , - . _ @.&lt;/li&gt;&lt;li&gt;may not contain spaces.&lt;/li&gt;&lt;li&gt;is not case sensitive (that is, upper and lower case versions of letters are treated the same).&lt;/li&gt;&lt;/ul&gt;.
        /// </summary>
        internal static string HintUserId {
            get {
                return ResourceManager.GetString("HintUserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have Other &quot;Annual&quot; Income?.
        /// </summary>
        internal static string PromptOtherAnnualIncome {
            get {
                return ResourceManager.GetString("PromptOtherAnnualIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have Other Income?.
        /// </summary>
        internal static string PromptOtherAnnualIncomeRetired {
            get {
                return ResourceManager.GetString("PromptOtherAnnualIncomeRetired", resourceCulture);
            }
        }
    }
}
